#:import menu menu

MainWidget:

<MainWidget>:
    canvas.before:
        Rectangle:
            size: self.size
            source: 'images/bg1.jpg'
    menu_widget: menu_widget
    perspective_point_x: self.width/2
    perspective_point_y: self.height * .95
    MenuWidget:
        id: menu_widget
    Label:
        text: root.score_txt
        font_name: 'fonts/Eurostile.ttf'
        font_size: dp(30)
        size_hint: .15, .1
        pos_hint: {"x": 0, "top": 1}
    